[package]
name = "math"
version = "0.1.0"
authors = ["Michael Grenier <grenim01@uqat.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.6.0"

[lib]
name = "math"
crate-type = ["rlib"]