[package]
name = "cli"
version = "0.1.0"
authors = ["Michael Grenier <grenim01@uqat.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"