[package]
name = "canvas"
version = "0.2.0"
edition = "2018"

[dependencies]
bitvec = { version = "0", features = ["serde"] }
color = { path = "../color" }
serde = { version = "1.0", features = ["rc"] }
vek = { version = "0.15", features = ["serde"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]