[package]
name = "document"
version = "0.1.0"
authors = ["Michael Grenier <grenim01@uqat.ca>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v1", "v4"] }
im = "14.3.0"
downcast-rs = "1.1.1"
math = { path = "../math" }

[lib]
name = "document"
crate-type = ["rlib"]